spring:
  application:
    name: biz-productor
  rabbitmq:
    port: 5672
    host: localhost
    username: anxiuze
    password: 123456
    template:
      exchange: "emailExchange"
      routing-key: "emailRouting"
    virtual-host: /anxiuze
server:
  port: 8081

